# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/modules/meta-schema.json
name: "rnamining"
description: "Predict coding potential from transcript FASTA sequences using RNAmining 1.1.0."
keywords:
  - "coding-potential"
  - "lncRNA"
  - "transcript-classification"
tools:
  - "rnamining":
      description: "Package to predict potential coding of RNA sequences provided in fasta format"
      homepage: "https://gitlab.com/integrativebioinformatics/RNAmining"
      documentation: "https://rnamining.integrativebioinformatics.me/"
      tool_dev_url: "https://gitlab.com/integrativebioinformatics/RNAmining"
      doi: "10.12688/f1000research.52350.2"
      licence: ["MIT"]
      identifier: "biotools:rnamining"

input:
  - fasta:
      type: file
      description: Transcript FASTA file with sequences to classify.
      pattern: "*.{fa,fasta,fna}"
      ontologies:
        - edam: "http://edamontology.org/format_1929"

output:
  codings:
    - codings_txt:
        type: file
        description: Predicted coding transcripts.
        pattern: "codings.txt"
        ontologies:
          - edam: "http://edamontology.org/data_2044"
            
  noncodings:
    - noncodings_txt:
        type: file
        description: Predicted non-coding transcripts.
        pattern: "noncodings.txt"
        ontologies:
          - edam: "http://edamontology.org/data_2044"
            
  predictions:
    - predictions_txt:
        type: file
        description: RNAMINING predictions as ID, prediction and score TSV rows.
        pattern: "predictions.txt"
        ontologies:
          - edam: "http://edamontology.org/data_2044"
            
  versions:
    - versions_yml:
        type: file
        description: File containing software versions
        pattern: "versions.yml"

authors:
  - "@lfreitasl"
maintainers:
  - "@lfreitasl"
